extends Node

var rosemary = 12
var charcoal = 5
var ginseng = 5
var ginger = 5
var nettle = 5
var thistle = 14
var lavender = 5
var yarrow = 5
var comfrey = 7
var valerian = 7
var mugwort = 17
var blue_lotus = 7
var mandrake = 7
var honey = 7
var plantain = 5
var billberry = 7
var garlic = 7
var eyebright = 7
var bonemeal = 9
var bones = 9
var bonemarrow = 9
var lucky_clover = 9

var rosemary_seed = 6 #0
var ginseng_seed = 4
var ginger_seed = 9
var nettle_seed = 10
var thistle_seed = 7 #0
var lavender_seed = 8 #0
var yarrow_seed = 6 #0
var comfrey_seed = 7
var valerian_seed = 5
var mugwort_seed = 6
var blue_lotus_seed = 3 # 0
var mandrake_seed = 6
var plantain_seed = 6
var billberry_seed = 5 #0
var garlic_seed = 7
var eyebright_seed = 8

#POTIONS
var potionhealth = 0
var potionmana = 0
var potionhealthvial = 0
var potionhealthbig = 0
var potionregenhealth = 0
var potionbindingdecoc = 0
var potionlife = 0
var potionregenbig = 6
var purifelixir = 0
var potionfireres = 0
var potionrejuv = 0
var potionundyingelixir = 0
var potionsimplepoison = 0
var potionvenomvial = 0
var potionbleedthorn = 0
var potiontirelessbrew = 0
var potionstamina = 0
var potionpotentstamina = 0
var potionhunting = 0
var potionawareness = 0
var potiondreamwalker = 0
var potionmanabig = 0
var potionmanaalt = 0
var potionluck = 0
var potioninvis = 0
var potionvenompurge = 0
var potionplagueward = 0
var potionblossom = 0

#POTIONRECIPES
var recipepotionhealth = true
var recipepotionmana = false
var recipepotionhealthvial = false
var recipepotionhealthbig = false
var recipepotionregenhealth = false
var recipepotionbindingdecoc = true
var recipepotionlife = false
var recipepotionregenbig = true
var recipepurifelixir = false
var recipepotionfireres = true
var recipepotionrejuv = false
var recipepotionundyingelixir = false
var recipepotionsimplepoison = false
var recipepotionvenomvial = false
var recipepotionbleedthorn = false
var recipepotiontirelessbrew = true
var recipepotionstamina = false
var recipepotionpotentstamina = false
var recipepotionhunting = false
var recipepotionawareness = false
var recipepotiondreamwalker = false
var recipepotionmanabig = true
var recipepotionmanaalt = false
var recipepotionluck = true
var recipepotioninvis = false
var recipepotionvenompurge = false
var recipepotionplagueward = false
var recipepotionblossom = true

var bread = 1
var wine = 4
var cheapwine = 2
var finewine = 4
var rawmeat = 2
